
import PDFDocument from 'pdfkit';

export async function GET() {

    const doc = new PDFDocument();

    let buffers = [];

    // Collect data as the PDF is being generated
    doc.on('data', (chunk) => buffers.push(chunk));

    // Return a Promise that resolves when the PDF is fully generated
    await new Promise((resolve) => {
        doc.on('end', resolve);

        // Add content to the PDF
        doc.text('Hello, this is a PDF generated by PDFKit!');
        doc.addPage();
        doc.text('This is the second page');

        // Finalize the PDF and end the stream
        doc.end();
    });

    // Concatenate all the chunks into a single buffer
    const pdfData = Buffer.concat(buffers);

    // Return the PDF as a response
    return new Response(pdfData, {
        headers: {
            'Content-Type': 'application/pdf',
            'Content-Disposition': 'inline' // open in page
            // 'Content-Disposition': 'attachment' // download
        }
    });
}